version: '3.8'
services:
  simplerest:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
      - 1883:1883
    depends_on:
      - timeScaledb
    volumes:
      - ./:/app/
    environment:
      - TZ=Europe/Paris

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile_subscriber
    networks:
     - db_network
    command: python subscriber.py

    depends_on:
      - simplerest
    volumes:
      - ./subscriber.py:/app/subscriber.py

  grafana:
    container_name: grafana
    image: grafana/grafana:6.5.0
    ports:
    - 3000:3000
    networks:
    - db_network

  timeScaledb:
    container_name: timeScaledb
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    networks:
      - db_network
    volumes: 
      - /data/timescaledb:/var/lib/postgresql/postgres_data
      - ./Database_Schema.sql:/docker-entrypoint-initdb.d/Database_Schema.sql
    environment:
      - PGDATA=/var/lib/postgresql/data/timescale/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cdlmint
      - POSTGRES_DB=cdl-mint

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db_network
    ports:
      - 5050:80
    depends_on:
      - timeScaledb

volumes:
  postgres_data:
networks:
  db_network:
    driver: bridge

