version: '3.8'
services:
  simplerest:
    container_name: smartroom_api
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
      - 1883:1883
    depends_on:
      - timeScaledb
    volumes:
      - ./api/:/app/
      - ./devices.json:/app/devices.json
    environment:
      - TZ=Europe/Paris

  subscriber:
    container_name: smartroom_mqtt_subscriber
    build:
      context: .
      dockerfile: Dockerfile_subscriber
    networks:
     - db_network
    command: python subscriber.py

    depends_on:
      - simplerest
    volumes:
      - ./devices.json:/app/devices.json

  grafana_smartroom:
    container_name: grafana_smartroom
    image: grafana/grafana:6.5.0
    ports:
    - 3001:3000
    networks:
    - db_network

  timeScaledb:
    container_name: timeScaledb
    image: timescale/timescaledb-ha:pg14-latest
    networks:
      - db_network
    volumes: 
      - /data/timescaledb:/var/lib/postgresql/postgres_data
      - ./database/Database_Schema.sql:/docker-entrypoint-initdb.d/Database_Schema.sql
    environment:
      - PGDATA=/var/lib/postgresql/data/timescale/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cdlmint
      - POSTGRES_DB=cdl-mint

  pgadmin_smartroom:
    container_name: pgadmin_smartroom
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db_network
    ports:
      - 5051:80
    depends_on:
      - timeScaledb

volumes:
  postgres_data:
  devices.json:
networks:
  db_network:
    driver: bridge

